### ISSUE TITLE
What is ListNotifier?

### ISSUE THREAD

**Issue by shaadart** [escamoteur/listenable_collections#6]
Hey Hi, 
I am having issues with the **ListNotifier()**
I am not able to understand its use, can anyone explain it... 

As from the example of this repo, it's pretty unclear.
As I am also trying to achieve this, 
```
  List<int> listenableList = [todoBox.length, completedBox.length];
  
  var _list = ListNotifier(data: listenableList);

```

**Comment by escamoteur** [comment]
It's like a `ChangeNotifier` but for Lists. Meaning you can register listeners to it or use it as Source for a `ValueListenableBuilder` and it will notify listeners whenever the List content changes

**Comment by shaadart** [comment]
Thanks @escamoteur for the fastest comment.
Thanks alot.

Can you give me Minimal Code Sample to Explain. please..

**Comment by escamoteur** [comment]
Do you know how ChangeNotifier and ValueNotifier work?

**Comment by shaadart** [comment]
Yes I had Worked with Value Notifier.. 
I have no idea of Change Notifier, Sir

**Comment by shaadart** [comment]
Yes, I had Worked with Value Notifier.. 
I have no idea of the Change Notifier, Sir. @escamoteur

**Comment by escamoteur** [comment]
ChangeNotifier is a parent class of ValueNotifier it also can notifiy listeners when changes happen.
If you have used ValueNotifier, what happens with a ValueNotifier<List<String>> if you add or remove an element of the List that is currently stored in the `value` property of that ValueNotifier?

**Comment by shaadart** [comment]
Oh yeah, I see, in your code, I Run that, It really worked like that... 
But i didnot saw, what separates any other packages like this from listenable_collections

**Comment by escamoteur** [comment]
when I wrote the package I didn't know that there are others that offer collection types that can be uses as ValueListenables.Have you found others?

**Comment by shaadart** [comment]
My dear, @escamoteur 

If you can check this one, 
https://pub.dartlang.org/packages/multi_value_listenable_builder

This also provides the functionality for multiple value listenables..

**Comment by escamoteur** [comment]
Just had a look at that package. But that is a builder widget that rebuilds depending on multiple ValueNotifiers, so doesn't solve the List case
